spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  datasource:
    url: jdbc:postgresql://${MYSQL_HOST:localhost}:5432/tour_operators_db
    username: postrges
    password: root
    initialization-mode: always

app:
  auth:
    password: root
    username: root